production:
  adapter: postgresql
  encoding: unicode
  database: api_bootstraper
  pool: 5
  username: api_bootstraper
  password:

development:
  adapter: mysql2
  encoding: utf8
  database: api_bootstraper_dev
  username: root
  password: 
  host: localhost
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  database: api_bootstraper_test
  pool: 30
  username: root
  password: 
  host: localhost
  port: 3306

# development:
#   adapter: postgresql
#   encoding: unicode
#   database: api_bootstraper_dev
#   pool: 5
#   username: postgres
#   password:
#   host: localhost
#   port: 5432
# 
# test:
#   adapter: postgresql
#   encoding: unicode
#   database: api_bootstraper_test
#   pool: 20
#   username: postgres
#   password:
#   host: localhost
#   port: 5432
# 
# staging:
#   adapter: postgresql
#   encoding: unicode
#   database: api_bootstraper_staging
#   pool: 5
#   username: postgres
#   password:
#   host: localhost
#   port: 5432
# 
# production:
#   adapter: postgresql
#   encoding: unicode
#   database: api_bootstraper
#   pool: 5
#   username: api_bootstraper
#   password:
